import math
import io
from datetime import date
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor

NAVY = HexColor("#1a3a5c")
GOLD = HexColor("#c47c2b")
LIGHT_GREY = HexColor("#f0f4f8")
MID_GREY = HexColor("#d0dce8")

def draw_survey_plan(survey_info, traverse_result):
    buffer = io.BytesIO()
    W, H = A4
    c = canvas.Canvas(buffer, pagesize=A4)
    c.setStrokeColor(NAVY)
    c.setLineWidth(3)
    c.rect(10*mm, 10*mm, W-20*mm, H-20*mm)
    c.setFillColor(NAVY)
    c.rect(12*mm, H-38*mm, W-24*mm, 22*mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 7)
    c.drawCentredString(W/2, H-20*mm, "FEDERAL REPUBLIC OF NIGERIA")
    c.setFont("Helvetica-Bold", 14)
    c.drawCentredString(W/2, H-27*mm, survey_info.get("state","").upper())
    c.setFont("Helvetica", 8)
    c.drawCentredString(W/2, H-33*mm, f"Survey Plan of Land at {survey_info.get('locality','')}")
    y = H-44*mm
    c.setStrokeColor(GOLD)
    c.setLineWidth(1.5)
    c.line(12*mm, y, W-12*mm, y)
    y -= 6*mm
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(NAVY)
    c.drawString(14*mm, y, "SURVEY DETAILS")
    y -= 6*mm
    fields = [("Surveyor", survey_info.get("surveyor_name","")), ("Owner", survey_info.get("client_name","")), ("Address", survey_info.get("plot_address","")), ("Locality", survey_info.get("locality","")), ("File No.", survey_info.get("file_no","")), ("Purpose", survey_info.get("purpose","")), ("Scale", survey_info.get("scale","")), ("Date", survey_info.get("survey_date",""))]
    for label, value in fields:
        c.setFont("Helvetica-Bold", 7)
        c.setFillColor(HexColor("#5a6a7a"))
        c.drawString(14*mm, y, f"{label}:")
        c.setFont("Helvetica", 7)
        c.setFillColor(NAVY)
        c.drawString(45*mm, y, str(value)[:50])
        y -= 6*mm
    y -= 4*mm
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(NAVY)
    c.drawString(14*mm, y, "SCHEDULE OF TRAVERSE")
    y -= 6*mm
    headers = ["Stn","Bearing","Dist(m)","Dep(m)","Lat(m)","Easting","Northing"]
    widths = [12,35,22,22,22,26,26]
    xs = [14*mm]
    for w in widths[:-1]:
        xs.append(xs[-1]+w*mm)
    c.setFillColor(NAVY)
    c.rect(14*mm, y-5*mm, sum(widths)*mm, 5*mm, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 6)
    for i,(h,x) in enumerate(zip(headers,xs)):
        c.drawCentredString(x+widths[i]*mm/2, y-4*mm, h)
    y -= 5*mm
    for idx,row in enumerate(traverse_result["rows"]):
        c.setFillColor(LIGHT_GREY if idx%2==0 else colors.white)
        c.rect(14*mm, y-5*mm, sum(widths)*mm, 5*mm, fill=1, stroke=0)
        vals = [row["station"],row["bearing"],f"{row['distance']:.3f}",f"{row['departure']:.3f}",f"{row['latitude']:.3f}",f"{row['easting']:.3f}",f"{row['northing']:.3f}"]
        for i,(v,x) in enumerate(zip(vals,xs)):
            c.setFont("Helvetica-Bold" if i==0 else "Helvetica", 6)
            c.setFillColor(GOLD if i==0 else NAVY)
            c.drawCentredString(x+widths[i]*mm/2, y-4*mm, str(v))
        y -= 5*mm
    y -= 8*mm
    for label,val in [("Perimeter",f"{traverse_result['perimeter_m']} m"),("Area",f"{traverse_result['area_sqm']} m² ({traverse_result['area_ha']} Ha)"),("Closure Error",f"{traverse_result['closure_error_m']} m"),("Precision",traverse_result['precision_ratio'])]:
        c.setFont("Helvetica-Bold", 7)
        c.setFillColor(HexColor("#5a6a7a"))
        c.drawString(14*mm, y, f"{label}:")
        c.setFont("Helvetica", 7)
        c.setFillColor(NAVY)
        c.drawString(50*mm, y, str(val))
        y -= 6*mm
    y -= 6*mm
    c.setStrokeColor(NAVY)
    c.setLineWidth(0.5)
    c.line(14*mm, y, W-14*mm, y)
    y -= 4*mm
    c.setFont("Helvetica", 6)
    c.setFillColor(HexColor("#888888"))
    c.drawString(14*mm, y, f"File No: {survey_info.get('file_no','')}")
    c.drawCentredString(W/2, y, "Generated by SurveyPlan Pro")
    c.drawRightString(W-14*mm, y, f"Date: {date.today().strftime('%d %B %Y')}")
    c.save()
    buffer.seek(0)
    return buffer.read()